x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  cp2k_opt:
    image: mycp2k-rtx5090:master_mpich_native_cuda_A100_psmp
    working_dir: /mnt/cp2k
    volumes:
      - .:/mnt/cp2k # Mount input/output directory
    gpus: "all"
    # shm_size: "8g"
    environment:
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - OMP_PLACES=cores
      - OMP_PROC_BIND=close
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DBCSR_ACC=1
    command: mpirun -np 1 cp2k.psmp -i aimd.inp -o aimd.log
    restart: "no"
    <<: *gpu
